name       : kmenuedit
version    : 5.25.3
release    : 81
source     :
    - https://cdn.download.kde.org/stable/plasma/5.25.3/kmenuedit-5.25.3.tar.xz : f792a1012b10118b13e8baa353fd014fc2051f35b2cb139b2a1b6491a8226778
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE Plasma menu editor
description: |
    KDE Plasma menu editor.
patterns   :
    - /usr/lib64/libkdeinit5*.so
optimize   : lto
builddeps  :
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - khotkeys-devel
    - kiconthemes-devel
    - kio-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
