name       : kmenuedit
version    : 5.18.3
release    : 47
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.3/kmenuedit-5.18.3.tar.xz : b508e780b23bc816812a4d025092e8dcc5373ed2f389e88f0c7beee8368d1e37
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma menu editor
description: |
    KDE Plasma menu editor.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdelibs4support-devel
    - kglobalaccel-devel
    - khotkeys-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
