name       : kmenuedit
version    : 5.26.3
release    : 82
source     :
    - https://cdn.download.kde.org/stable/plasma/5.26.3/kmenuedit-5.26.3.tar.xz : 7c073853dc2cf97fd09c5b8939365777068a4671432f8cf84312ba145dd6572d
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE Plasma menu editor
description: |
    KDE Plasma menu editor.
patterns   :
    - /usr/lib64/libkdeinit5*.so
optimize   : lto
builddeps  :
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - khotkeys-devel
    - kiconthemes-devel
    - kio-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
