name       : kmenuedit
version    : 5.16.1
release    : 34
source     :
    - https://download.kde.org/stable/plasma/5.16.1/kmenuedit-5.16.1.tar.xz : 34f7c3e01c54d94a597a26e88f610738995a7db02dc526e00fdd11f9886c3056
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma menu editor
description: |
    KDE Plasma menu editor.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdelibs4support-devel
    - khotkeys-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
