name       : kmenuedit
version    : 5.17.5
release    : 44
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.5/kmenuedit-5.17.5.tar.xz : 59beed03298cd9fd6b05d67844794ed6a77be0d1b25b55d5bbcdf72e15e357de
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma menu editor
description: |
    KDE Plasma menu editor.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdelibs4support-devel
    - khotkeys-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
