name       : kmenuedit
version    : 5.24.4
release    : 78
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.4/kmenuedit-5.24.4.tar.xz : 147a7e9a15393375c2b22b5dfb025a87f3356cf756cf3b17615ba989bb443466
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE Plasma menu editor
description: |
    KDE Plasma menu editor.
patterns   :
    - /usr/lib64/libkdeinit5*.so
optimize   : lto
builddeps  :
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - khotkeys-devel
    - kiconthemes-devel
    - kio-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
