name       : kmenuedit
version    : 5.16.3
release    : 36
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.3/kmenuedit-5.16.3.tar.xz : 2ccc8e7feea7b4d3616a7528cf65a62c5299388583afb295d0aa2379945035cd
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma menu editor
description: |
    KDE Plasma menu editor.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdelibs4support-devel
    - khotkeys-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
