name       : kmenuedit
version    : 5.10.5
release    : 3
source     :
    - https://download.kde.org/stable/plasma/5.10.5/kmenuedit-5.10.5.tar.xz : 5555aacc9b97d8c64073fa5007659520bbf4fc4996f50d036e2381fa0a35e82c
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
summary    : KDE Plasma menu editor
description: |
    KDE Plasma menu editor.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdbusaddons-devel
    - kdelibs4support-devel
    - khotkeys-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kxmlgui-devel
    - sonnet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
