name       : kmenuedit
version    : 5.19.5
release    : 54
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.5/kmenuedit-5.19.5.tar.xz : f4701c74c304d46f5146943aa297300fb38a9c3b1efad39d4fbf3238d49989f6
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma menu editor
description: |
    KDE Plasma menu editor.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdelibs4support-devel
    - kglobalaccel-devel
    - khotkeys-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/HTML
