name       : kmenuedit
version    : 5.19.2
release    : 50
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.2/kmenuedit-5.19.2.tar.xz : a64cbe07168e5e67bb4ea2d3394c12ac73c84d4df560038e476146d9f98bfa32
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma menu editor
description: |
    KDE Plasma menu editor.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdelibs4support-devel
    - kglobalaccel-devel
    - khotkeys-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
